server:
  port: 8083
  
spring:
  application:
    name: rating-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservice

eureka:
  instance:
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defultZone: http://localhost:8762/eureka

okta:
  oauth2:
    issuer: https://dev-41002044.okta.com/oauth2/default
    audience: api://default