spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
       
#  config:
#    import: optional:configserver:http://localhost:8085
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  https://dev-41002044.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa8heuapt6XMS6mw5d7
            client-secret: w74uw2Ol-voRhzGFhwStGfglko-z5Ye_sYfRcc9z

        provider:
          okta:
            issuer-uri: https://dev-41002044.okta.com/oauth2/default
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defultZone: http://localhost:8763/eureka
      
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

okta:
  oauth2:
    issuer: https://dev-41002044.okta.com/oauth2/default
    audience: api://default


server:
  port: 8081